In [1]:
import pandas as pd

In [25]:
df=pd.read_csv(r'D:\Users\ankit\medical.csv')
df

,Patient_ID,Age,Gender,Blood_Pressure,Cholesterol,BMI,Smoker,Diagnosis,Admission_Date,Notes
0,P1000,55.0,FEMALE,120.0,NaN,35.4,Yes,Heart Disease,2023-12-27,NaN
1,P1001,65.0,Male,150.0,180.0,27.8,NaN,NaN,2023-01-01,NaN
2,P1002,45.0,Male,120.0,220.0,22.5,No,NaN,2023-12-14,NaN
3,P1003,65.0,Male,NaN,180.0,35.4,No,NaN,2023-07-09,NaN
4,P1004,65.0,Male,120.0,300.0,40.1,NaN,NaN,2023-07-10,Follow-up required
...,...,...,...,...,...,...,...,...,...,...
95,P1095,55.0,MALE,150.0,200.0,35.4,Yes,NaN,2023-07-16,Follow-up required
96,P1096,55.0,male,NaN,220.0,27.8,Y,NaN,2023-12-17,Follow-up required
97,P1097,65.0,Female,150.0,200.0,27.8,N,NaN,2023-05-13,Checkup due
98,P1098,25.0,MALE,NaN,180.0,40.1,Yes,Diabetes,2023-12-24,Follow-up required
99,P1099,65.0,NaN,140.0,300.0,35.4,N,NaN,2023-09-16,NaN

In [30]:
x=df['Blood_Pressure'].mean()
df.fillna({'Blood_Pressure':x},inplace=True)
df

,Patient_ID,Age,Gender,Blood_Pressure,Cholesterol,BMI,Smoker,Diagnosis,Admission_Date,Notes
0,P1000,55.0,FEMALE,120.000000,NaN,35.4,Yes,Heart Disease,2023-12-27,NaN
1,P1001,65.0,Male,150.000000,180.0,27.8,NaN,NaN,2023-01-01,NaN
2,P1002,45.0,Male,120.000000,220.0,22.5,No,NaN,2023-12-14,NaN
3,P1003,65.0,Male,137.093023,180.0,35.4,No,NaN,2023-07-09,NaN
4,P1004,65.0,Male,120.000000,300.0,40.1,NaN,NaN,2023-07-10,Follow-up required
...,...,...,...,...,...,...,...,...,...,...
95,P1095,55.0,MALE,150.000000,200.0,35.4,Yes,NaN,2023-07-16,Follow-up required
96,P1096,55.0,male,137.093023,220.0,27.8,Y,NaN,2023-12-17,Follow-up required
97,P1097,65.0,Female,150.000000,200.0,27.8,N,NaN,2023-05-13,Checkup due
98,P1098,25.0,MALE,137.093023,180.0,40.1,Yes,Diabetes,2023-12-24,Follow-up required
99,P1099,65.0,NaN,140.000000,300.0,35.4,N,NaN,2023-09-16,NaN

In [31]:
x=df['Age'].mean()
df.fillna({'Age':x},inplace=True)
df

,Patient_ID,Age,Gender,Blood_Pressure,Cholesterol,BMI,Smoker,Diagnosis,Admission_Date,Notes
0,P1000,55.0,FEMALE,120.000000,NaN,35.4,Yes,Heart Disease,2023-12-27,NaN
1,P1001,65.0,Male,150.000000,180.0,27.8,NaN,NaN,2023-01-01,NaN
2,P1002,45.0,Male,120.000000,220.0,22.5,No,NaN,2023-12-14,NaN
3,P1003,65.0,Male,137.093023,180.0,35.4,No,NaN,2023-07-09,NaN
4,P1004,65.0,Male,120.000000,300.0,40.1,NaN,NaN,2023-07-10,Follow-up required
...,...,...,...,...,...,...,...,...,...,...
95,P1095,55.0,MALE,150.000000,200.0,35.4,Yes,NaN,2023-07-16,Follow-up required
96,P1096,55.0,male,137.093023,220.0,27.8,Y,NaN,2023-12-17,Follow-up required
97,P1097,65.0,Female,150.000000,200.0,27.8,N,NaN,2023-05-13,Checkup due
98,P1098,25.0,MALE,137.093023,180.0,40.1,Yes,Diabetes,2023-12-24,Follow-up required
99,P1099,65.0,NaN,140.000000,300.0,35.4,N,NaN,2023-09-16,NaN

In [55]:
x=df['Cholesterol'].mean()
df.fillna({'Cholesterol':x},inplace=True)
df

,Patient_ID,Age,Gender,Blood_Pressure,Cholesterol,BMI,Smoker,Diagnosis,Admission_Date,Notes
0,P1000,55.0,Female,120.000000,226.75,35.4,Yes,Heart Disease,2023-12-27,NaN
1,P1001,65.0,Male,150.000000,180.00,27.8,NaN,NaN,2023-01-01,NaN
2,P1002,45.0,Male,120.000000,220.00,22.5,No,NaN,2023-12-14,NaN
3,P1003,65.0,Male,137.093023,180.00,35.4,No,NaN,2023-07-09,NaN
4,P1004,65.0,Male,120.000000,300.00,40.1,NaN,NaN,2023-07-10,Follow-up required
...,...,...,...,...,...,...,...,...,...,...
95,P1095,55.0,Male,150.000000,200.00,35.4,Yes,NaN,2023-07-16,Follow-up required
96,P1096,55.0,male,137.093023,220.00,27.8,Yes,NaN,2023-12-17,Follow-up required
97,P1097,65.0,Female,150.000000,200.00,27.8,No,NaN,2023-05-13,Checkup due
98,P1098,25.0,Male,137.093023,180.00,40.1,Yes,Diabetes,2023-12-24,Follow-up required
99,P1099,65.0,NaN,140.000000,300.00,35.4,No,NaN,2023-09-16,NaN

In [43]:
df.replace('N', 'No', inplace=True)
df.replace('Y', 'Yes', inplace=True)
df

,Patient_ID,Age,Gender,Blood_Pressure,Cholesterol,BMI,Smoker,Diagnosis,Admission_Date,Notes
0,P1000,55.0,FEMALE,120.000000,226.75,35.4,Yes,Heart Disease,2023-12-27,NaN
1,P1001,65.0,Male,150.000000,180.00,27.8,NaN,NaN,2023-01-01,NaN
2,P1002,45.0,Male,120.000000,220.00,22.5,No,NaN,2023-12-14,NaN
3,P1003,65.0,Male,137.093023,180.00,35.4,No,NaN,2023-07-09,NaN
4,P1004,65.0,Male,120.000000,300.00,40.1,NaN,NaN,2023-07-10,Follow-up required
...,...,...,...,...,...,...,...,...,...,...
95,P1095,55.0,MALE,150.000000,200.00,35.4,Yes,NaN,2023-07-16,Follow-up required
96,P1096,55.0,male,137.093023,220.00,27.8,Yes,NaN,2023-12-17,Follow-up required
97,P1097,65.0,Female,150.000000,200.00,27.8,No,NaN,2023-05-13,Checkup due
98,P1098,25.0,MALE,137.093023,180.00,40.1,Yes,Diabetes,2023-12-24,Follow-up required
99,P1099,65.0,NaN,140.000000,300.00,35.4,No,NaN,2023-09-16,NaN

In [54]:
# Replaces the literal string 'NaN' with Python's None object in the 'Smoker' column
df['Gender'] = df['Gender'].replace('MALE', 'Male')
df['Gender'] = df['Gender'].replace('FEMALE', 'Female')
df

,Patient_ID,Age,Gender,Blood_Pressure,Cholesterol,BMI,Smoker,Diagnosis,Admission_Date,Notes
0,P1000,55.0,Female,120.000000,226.75,35.4,Yes,Heart Disease,2023-12-27,NaN
1,P1001,65.0,Male,150.000000,180.00,27.8,NaN,NaN,2023-01-01,NaN
2,P1002,45.0,Male,120.000000,220.00,22.5,No,NaN,2023-12-14,NaN
3,P1003,65.0,Male,137.093023,180.00,35.4,No,NaN,2023-07-09,NaN
4,P1004,65.0,Male,120.000000,300.00,40.1,NaN,NaN,2023-07-10,Follow-up required
...,...,...,...,...,...,...,...,...,...,...
95,P1095,55.0,Male,150.000000,200.00,35.4,Yes,NaN,2023-07-16,Follow-up required
96,P1096,55.0,male,137.093023,220.00,27.8,Yes,NaN,2023-12-17,Follow-up required
97,P1097,65.0,Female,150.000000,200.00,27.8,No,NaN,2023-05-13,Checkup due
98,P1098,25.0,Male,137.093023,180.00,40.1,Yes,Diabetes,2023-12-24,Follow-up required
99,P1099,65.0,NaN,140.000000,300.00,35.4,No,NaN,2023-09-16,NaN

In [57]:
df.drop_duplicates(inplace = True)
df

,Patient_ID,Age,Gender,Blood_Pressure,Cholesterol,BMI,Smoker,Diagnosis,Admission_Date,Notes
0,P1000,55.0,Female,120.000000,226.75,35.4,Yes,Heart Disease,2023-12-27,NaN
1,P1001,65.0,Male,150.000000,180.00,27.8,NaN,NaN,2023-01-01,NaN
2,P1002,45.0,Male,120.000000,220.00,22.5,No,NaN,2023-12-14,NaN
3,P1003,65.0,Male,137.093023,180.00,35.4,No,NaN,2023-07-09,NaN
4,P1004,65.0,Male,120.000000,300.00,40.1,NaN,NaN,2023-07-10,Follow-up required
...,...,...,...,...,...,...,...,...,...,...
95,P1095,55.0,Male,150.000000,200.00,35.4,Yes,NaN,2023-07-16,Follow-up required
96,P1096,55.0,male,137.093023,220.00,27.8,Yes,NaN,2023-12-17,Follow-up required
97,P1097,65.0,Female,150.000000,200.00,27.8,No,NaN,2023-05-13,Checkup due
98,P1098,25.0,Male,137.093023,180.00,40.1,Yes,Diabetes,2023-12-24,Follow-up required
99,P1099,65.0,NaN,140.000000,300.00,35.4,No,NaN,2023-09-16,NaN

In [ ]:
df.to_excel('medical.', index=False)