In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
labels=['a','b','c']
my_list=[10,20,30]
arr=np.array([10,20,30])
d={'a':10,'b':20,'c':30}
pd.Series(data=my_list)

0    10
1    20
2    30
dtype: int64

In [4]:
pd.Series(arr,labels)

a    10
b    20
c    30
dtype: int64

In [5]:
pd.Series(data=labels)

0    a
1    b
2    c
dtype: object

In [6]:
pd.Series([sum,print,len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [7]:
ser1=pd.Series([1,2,3,4],index=['USA','GERMANY','USSR','JAPAN'])

In [8]:
ser1

USA        1
GERMANY    2
USSR       3
JAPAN      4
dtype: int64

In [9]:
ser2=pd.Series([1,2,5,4],index=['USA','GERMANY','USSR','JAPAN'])

In [10]:
ser2

USA        1
GERMANY    2
USSR       5
JAPAN      4
dtype: int64

In [11]:
ser1['USA']

np.int64(1)

In [2]:
import numpy as np

In [19]:
import pandas as pd
from numpy.random import randn
np.random.seed(101)

In [18]:
df=pd.DataFrame(randn(5,4), index='A B C D E'.split(),columns='W X Y Z'.split())

In [10]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [13]:
df['W']

A    0.302665
B   -0.134841
C    0.807706
D   -0.497104
E   -0.116773
Name: W, dtype: float64

In [15]:
df[['W','Z']]

          W         Z
A  0.302665 -1.159119
B -0.134841  0.184502
C  0.807706  0.329646
D -0.497104  0.484752
E -0.116773  1.996652

In [20]:
df.W

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [21]:
df['new']=df['W']+df['Y'] #add new columns

In [22]:
df

          W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [23]:
df.drop('new',axis=1) # for delete column

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [24]:
df.drop('new',axis=1,inplace=True)

In [25]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [26]:
df.drop('E',axis=0)

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

In [27]:
df.loc['A'] # salecting rows

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [28]:
df.iloc[2]

W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64

In [29]:
df.iloc[3]

W    0.188695
X   -0.758872
Y   -0.933237
Z    0.955057
Name: D, dtype: float64

In [30]:
df.loc['B','Y']

np.float64(-0.8480769834036315)

In [32]:
df.loc[['A','B'],['W','Y']]

          W         Y
A  2.706850  0.907969
B  0.651118 -0.848077

In [33]:
df.loc[['A','C'],['W','Z']]

          W         Z
A  2.706850  0.503826
C -2.018168 -0.589001

In [34]:
df.loc[['A','D'],['X','Y']]

          X         Y
A  0.628133  0.907969
D -0.758872 -0.933237

In [35]:
import pandas as pd

In [36]:
import numpy as np

In [37]:
df>0

       W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [38]:
df[df>0]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [39]:
df[df['X']>0]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
C -2.018168  0.740122  0.528813 -0.589001
E  0.190794  1.978757  2.605967  0.683509

In [43]:
df[df['X']>0][['Y','W']]

          Y         W
A  0.907969  2.706850
C  0.528813 -2.018168
E  2.605967  0.190794

In [41]:
df[df['W']>0]['Y']

A    0.907969
B   -0.848077
D   -0.933237
E    2.605967
Name: Y, dtype: float64

In [42]:
df[df['X']>0]['Y']

A    0.907969
C    0.528813
E    2.605967
Name: Y, dtype: float64

In [48]:
df[(df['W']>0) & (df['Y']>1)]

          W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

In [49]:
df[(df['W']>0) | (df['Y']>1)]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [50]:
df.reset_index()

  index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [69]:
newind ='CA NY WY OR CO'.split()

In [70]:
df['States'] = newind

In [71]:
df

,W,X,Y,Z,States
States,,,,,
<built-in method split of str object at 0x0000018C2989A1B0>,2.706850,0.628133,0.907969,0.503826,CA
<built-in method split of str object at 0x0000018C2989A1B0>,0.651118,-0.319318,-0.848077,0.605965,NY
<built-in method split of str object at 0x0000018C2989A1B0>,-2.018168,0.740122,0.528813,-0.589001,WY
<built-in method split of str object at 0x0000018C2989A1B0>,0.188695,-0.758872,-0.933237,0.955057,OR
<built-in method split of str object at 0x0000018C2989A1B0>,0.190794,1.978757,2.605967,0.683509,CO

In [72]:
df.set_index('States',inplace=True)

In [73]:
df

               W         X         Y         Z
States
CA      2.706850  0.628133  0.907969  0.503826
NY      0.651118 -0.319318 -0.848077  0.605965
WY     -2.018168  0.740122  0.528813 -0.589001
OR      0.188695 -0.758872 -0.933237  0.955057
CO      0.190794  1.978757  2.605967  0.683509

In [74]:
df =pd.DataFrame({'A':[1,2,np.nan],'B':[5,np.nan,np.nan],'C':[1,2,3]})

In [75]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [76]:
df.dropna()

     A    B  C
0  1.0  5.0  1

In [77]:
df.dropna(axis=1)

   C
0  1
1  2
2  3

In [78]:
df.fillna(value='FILL VALUE')

            A           B  C
0         1.0         5.0  1
1         2.0  FILL VALUE  2
2  FILL VALUE  FILL VALUE  3

In [1]:
import pandas as pd
import numpy as np

In [4]:
pd.read_excel(r'D:\data3.xlsx')

ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.